server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: UTF-8
    suffix: .html

mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis.cfg.xml

logging:
  config: classpath:logback-spring.xml





#自定义标签
app:
  appname: springBootMybatis
  appcopyright: This is a springBoot demo
  appyear: 1990-2018

#mybatis分页插件
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql





